/*
 * This header file is auto-generated from pttbbs/mbbsd/var.c .
 * Please do NOT edit this file directly.
 */

#ifndef INCLUDE_VAR_H
#define INCLUDE_VAR_H

#include "pttstruct.h"
#include "common.h"

extern char * const fn_board ;
extern const char * const fn_visable ;
extern time4_t         now;
extern time4_t         login_start_time, last_login_time;
extern SHM_t          *SHM;
extern boardheader_t  *bcache;
#ifdef PTTBBS_UTIL
    #define COMMON_TIME (time(0))
#else
    #define COMMON_TIME (now)
#endif
#endif /* INCLUDE_VAR_H */
